### ISSUE TITLE
ATC Names

### ISSUE THREAD

**Issue by lmcewen** [interstellar-Consultation-Services/dbdataset#2]
I have been working with the dbparser package to query the drugbank xml file and now have been using the dbdataset package (amazing work - thank you!); however, I have an issue I keep running into. My goal is to create a file (csv) that contains a list of drug name synonyms with their associated ATC codes. The reason for this is because I work for a health authority that has electronic medical records for all pharmacy orders. The data I get has "order name" that, for the majority of the time, matches the Health Canada/WHO exports so I can easily retrieve the ATC code from that source; although, there are several (~2000) drug names that do not match the Health Canada or WHO files and this is because they are not a direct name match as they are synonyms of the drug. With that, the drugbank's synonym list is exactly what we need to help us get better matching coverage. I am joining the drugbank ATC and Synonym tables but have a problem in that there are some ATC codes that have the same drug ID so it is impossible, with this approach, to determine which is the correct ATC Code. For example, ATC codes N02BE01 and N02BE51: N02BE51 should be paracetamol + combinations; whereas, N02BE01 should be only paracetamol. 

### R Code:

```{r}
atc <- dbdataset::ATC_Codes_Drug
syn <- dbdataset::Synonyms_Drug

atc_syn <- atc %>%
  full_join(syn, by = "parent_key")

#just filtering out ATC codes that have a single drug 
single_drugs <- atc_syn %>%
  group_by(atc_code)%>%
  mutate(n=n_distinct(parent_key))%>%
  filter(n==1) 

#now subsetting the drugs that have more than one ATC code
single_drugs_multi_atc <- single_drugs %>%
  group_by(parent_key)%>%
  mutate(n_atc=n_distinct(atc_code))%>%
  filter(n_atc>1)

n_distinct(single_drugs_multi_atc$parent_key) 
#573 have more than 1 atc code (where the atc code only had a single drug parent key)

subset(single_drugs_multi_atc, atc_code == "N02BE51") 
#should be paracetmol + combinations excl. psycholeptics 

subset(single_drugs_multi_atc, atc_code == "N02BE01") 
#correct name
```

In these data they both look like it is just paracetamol (parent key = DB00316). There are also many other cases like this. Do you know of another table I could use or approach I could take to resolve this? It is a problem for us because if we use this table and match on name it will pull two ATC codes for a single drug name (in this case "paracetamol").

**Comment by MohammedFCIS** [comment]
Dear @lmcewen ,
Thank you so much for using our packages and submitting your first issue.
Please know that your issue is under review now and I will be back to you with an answer shortly :).
Best Regards,

**Comment by alizat** [comment]
Dear @lmcewen,
I have looked into the issue that you raised above. Unfortunately, it seems that you found a particular scenario that is currently not possible to resolve using **dbdataset**.

Ideally the data frame, `dbdataset::ATC_Codes_Drug`, would have an extra column containing the _names_ corresponding to the different ATC codes (e.g. `paracetmol + combinations excl. psycholeptics`). At present, only the _levels_ of the ATC codes are given in `dbdataset::ATC_Codes_Drug`.

The reason that the ATC names are not included in `dbdataset::ATC_Codes_Drug` is as follows:
**dbdataset** was generated from the latest release of the DrugBank database which is downloadable in XML format from [here](https://www.drugbank.ca/releases/latest). While the downloadable XML database contains most of the data available at the DrugBank website, one of the fields that are missing from the XML database happens to be the ATC names that you are seeking.

For the time being, a possible workaround is to perform web scraping on the [DrugBank's ATC list](https://www.drugbank.ca/atc) webpage. Doing so, you will be able to generate a data frame containing the ATC codes and their corresponding names. You may then _join_ this data frame with the `atc_syn` data frame from your code to get a final data frame containing the drugs and their corresponding ATC names.

In the future, we intend to add the ATC names as a column in the `dbdataset::ATC_Codes_Drug` data frame. Please let us know if you have any further inquiries.

Yours Sincerely,
The Dainanahan Team
