### ISSUE TITLE
Extract SMILES data

### ISSUE THREAD

**Issue by owengwydionjames** [interstellar-Consultation-Services/dbdataset#4]
Hi Mohammed,

Sorry for the novice question but could you please explain how to extract SMILES data from the dbdataset tibbles please? 

Many thanks in advance!

**Comment by MohammedFCIS** [comment]
Hello @OwenGwyd,
Unfortunately, DrugBank database does not contain SMILES information at its database as SMILES information are stored in another database.

The only information stored in DrugBank is about Molecular Formula and targets sequence and to extract that please review this post https://github.com/ropensci/dbparser/issues/83.

However; the good new is that we can retrieve SMILEs using DrugBank Id easily using [Rcpi](https://www.bioconductor.org/packages/release/bioc/html/Rcpi.html)

see the following example:
`smiles <- Rcpi::getSmiFromDrugBank(c('DB12491', 'DB01075')) `

On the other hand, kindly be informed that there is under going project called [drugverse](https://dainanahan.github.io/drugverse/) that aims to implement different data science tools specialized in drugs development. It will be kind of you if you reviewed that project and created issues in each package to sate your and your fellow researchers needs so we can take it into consideration.
Thank you
