### ISSUE TITLE
Gene Name of Drug Targets

### ISSUE THREAD

**Issue by FenghuJi** [interstellar-Consultation-Services/dbdataset#9]
Hi,Dainanahan
Your package provides convenience for us. And now I hava a gene lists of interest. I want to find what drug can target them. 
Now I have a list of drugs for a kind of disease and a list of genes taking genetic variants raised by the disease. I want to get the interaction between the drugs and the genes with the information in DrugBank.
Now your `Targets_Drug` provides only the UniPROT generic name but no gene names. So I can't direct do such mapping work. Can you add information of **Gene Symbol** or **UniPROT id**  for the function `Targets_Drug` ? Or can you recommend any method to do such mapping work? Thanks a lot.
Best wishes,
Fenghu Ji

**Comment by MohammedFCIS** [comment]
Hi @FenghuJi ,
Thank you for submitting your issue.
I will review it and reply ASAP.
Best Regards,
Mohammed Ali

**Comment by MohammedFCIS** [comment]
Hi @FenghuJi ,
There are 11 datasets related to drug targets including **Targets_Drug**, please review the architecture here https://dainanahan.github.io/dbdataset/articles/dbdataset.html.
Gene name is found, and other gene related information, can be found in **Polypeptide_Target_Drug** dataset.
Please use ```?Polypeptide_Target_Drug``` for more information.
Please let me know if further help is need.
Best Regards,
Mohammed
